format = '''$directory$git_branch$git_status$cmd_duration$character'''
add_newline = false

[git_branch]
symbol = ''
style = ''

[character]
success_symbol = '[\$](bold green)'
error_symbol = '[\$](bold red)'
